version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./config/otel/config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55681:55681"
